### ISSUE TITLE
Accessibility in core-focusable

### ISSUE THREAD

**Issue by Nevraeka** [Polymer/core-focusable#7]
copied from [Polymer/Polymer issue #1081](https://github.com/Polymer/polymer/issues/1081) posted by @hcarmona 
>
> In https://github.com/Polymer/core-focusable/blob/master/core-focusable.js
> `this.setAttribute('aria-disabled', '');`
> should be changed to
> `this.setAttribute('aria-disabled', 'true');`
>
> This is because aria-disabled must have a value of true or false. Empty string is invalid and the default > value is false. [http://www.w3.org/TR/wai-aria/states_and_properties#aria-disabled](http://www.w3.org/TR/wai-aria/states_and_properties#aria-disabled)

**Comment by cdata** [comment]
This will be addressed by #12 .

**Comment by Nevraeka** [comment]
thank you @cdata
